version: "3.8"

services:
  backend:
    image: sashank662/concept_accessor_backend:Mar6
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - libretranslate
    environment:
      - LIBRETRANSLATE_URL=http://libretranslate:5000

  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    ports:
      - "5000:5000"